spring:
  profiles:
    default: ollama
  application:
    name: personal-finance-service
  datasource:
    url: jdbc:h2:mem:personal_finance;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

mail:
  listener:
    enabled: true
    host: "localhost"
    port: 143
    username: "any"
    password: "any"
    protocol: imap
    folder: INBOX
    subject-text: "c6 notification"
    cron-expression: "0 */1 * * * *"
    ssl-enable: false
    starttls-enable: false
    mark-as-read: true

twilio:
  whatsapp:
    account-sid: "${TWILIO_WHATSAPP_ACCOUNT_SID:}"
    auth-token: "${TWILIO_WHATSAPP_AUTH_TOKEN:}"
    from-number: "${TWILIO_WHATSAPP_FROM_NUMBER:}"
    transaction-template-id: "${TWILIO_WHATSAPP_TRANSACTION_TEMPLATE_ID:}"

finance:
  rag:
    enabled: true
    path: "rag"
    max-segment-size: 1000
    max-overlap-size: 200
  expense-analysis:
    scheduler:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web.client.DefaultRestClient: DEBUG
    dev.langchain4j: DEBUG
    com.twilio: DEBUG
    org.apache.http: INFO
    org.apache.http.headers: INFO
    org.apache.http.impl.conn: INFO
    org.apache.http.wire: INFO
