spring.application.name=personal-finance-service

mail.listener.enabled=false
mail.listener.host=
mail.listener.port=993
mail.listener.username=
mail.listener.password=
mail.listener.protocol=imaps
mail.listener.folder=INBOX
mail.listener.poll-interval-ms=60000
mail.listener.ssl-enable=true
mail.listener.starttls-enable=false
mail.listener.mark-as-read=true
