langchain4j:
  open-ai:
    chat-model:
      api-key: "${OPENAI_API_KEY:}"
      base-url: "https://api.openai.com/v1"
      model-name: "${OPENAI_CHAT_MODEL:gpt-4o-mini}"
      timeout: "PT240S"
    embedding-model:
      api-key: "${OPENAI_API_KEY:}"
      base-url: "https://api.openai.com/v1"
      model-name: "${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}"
      timeout: "PT240S"
