spring:
  application:
    name: personal-finance-service
  datasource:
    url: jdbc:h2:mem:personal_finance;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

mail:
  listener:
    enabled: true
    host: "localhost"
    port: 143
    username: "any"
    password: "any"
    protocol: imap
    folder: INBOX
    subject-text: "c6 notification"
    cron-expression: "0 */1 * * * *"
    ssl-enable: false
    starttls-enable: false
    mark-as-read: true

langchain4j:
  ollama:
    chat-model:
      base-url: "http://localhost:11434"
      model-name: "qwen2.5-coder:3b"
      timeout: "PT240S"
    embedding-model:
      base-url: "http://localhost:11434"
      model-name: "nomic-embed-text"
      timeout: "PT240S"

finance:
  rag:
    path: "src/main/resources/rag"
    max-segment-size: 1000
    max-overlap-size: 200

logging:
  level:
    root: INFO
    org.springframework.web.client.DefaultRestClient: DEBUG
    dev.langchain4j: DEBUG

